# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineageM_diary.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(877, 388)
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.left_btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn1.setGeometry(QtCore.QRect(20, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.left_btn1.setFont(font)
        self.left_btn1.setObjectName("left_btn1")
        self.left_btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.left_btn2.setGeometry(QtCore.QRect(20, 170, 101, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.left_btn2.setFont(font)
        self.left_btn2.setObjectName("left_btn2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 111, 40))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.cb_vmtype = QtWidgets.QComboBox(self.centralwidget)
        self.cb_vmtype.setGeometry(QtCore.QRect(140, 10, 91, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.cb_vmtype.setFont(font)
        self.cb_vmtype.setObjectName("cb_vmtype")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 161, 40))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.cb_vmsize = QtWidgets.QComboBox(self.centralwidget)
        self.cb_vmsize.setGeometry(QtCore.QRect(140, 50, 91, 30))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.cb_vmsize.setFont(font)
        self.cb_vmsize.setObjectName("cb_vmsize")
        self.left_ghView1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.left_ghView1.setGeometry(QtCore.QRect(140, 110, 51, 41))
        self.left_ghView1.setObjectName("left_ghView1")
        self.left_ghView2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.left_ghView2.setGeometry(QtCore.QRect(140, 170, 51, 41))
        self.left_ghView2.setObjectName("left_ghView2")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(20, 290, 181, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName("start_btn")
        self.end_btn = QtWidgets.QPushButton(self.centralwidget)
        self.end_btn.setGeometry(QtCore.QRect(240, 290, 181, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.end_btn.setFont(font)
        self.end_btn.setObjectName("end_btn")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 240, 221, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.right_btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.right_btn1.setGeometry(QtCore.QRect(240, 110, 101, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.right_btn1.setFont(font)
        self.right_btn1.setObjectName("right_btn1")
        self.right_ghView1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.right_ghView1.setGeometry(QtCore.QRect(350, 110, 51, 41))
        self.right_ghView1.setObjectName("right_ghView1")
        self.right_btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.right_btn2.setGeometry(QtCore.QRect(240, 170, 101, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.right_btn2.setFont(font)
        self.right_btn2.setObjectName("right_btn2")
        self.right_ghView2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.right_ghView2.setGeometry(QtCore.QRect(350, 170, 51, 41))
        self.right_ghView2.setObjectName("right_ghView2")
        self.hs_diarycount = QtWidgets.QSlider(self.centralwidget)
        self.hs_diarycount.setGeometry(QtCore.QRect(240, 249, 161, 20))
        self.hs_diarycount.setMinimum(1)
        self.hs_diarycount.setMaximum(10)
        self.hs_diarycount.setOrientation(QtCore.Qt.Horizontal)
        self.hs_diarycount.setObjectName("hs_diarycount")
        self.lab_displaydiraycount = QtWidgets.QLabel(self.centralwidget)
        self.lab_displaydiraycount.setGeometry(QtCore.QRect(410, 243, 31, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(14)
        self.lab_displaydiraycount.setFont(font)
        self.lab_displaydiraycount.setObjectName("lab_displaydiraycount")
        self.lab_sysmsg = QtWidgets.QLabel(self.centralwidget)
        self.lab_sysmsg.setGeometry(QtCore.QRect(480, 10, 91, 41))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.lab_sysmsg.setFont(font)
        self.lab_sysmsg.setObjectName("lab_sysmsg")
        self.setdevice_btn = QtWidgets.QPushButton(self.centralwidget)
        self.setdevice_btn.setGeometry(QtCore.QRect(360, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.setdevice_btn.setFont(font)
        self.setdevice_btn.setObjectName("setdevice_btn")
        self.txt_sysmsg = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sysmsg.setGeometry(QtCore.QRect(480, 50, 391, 291))
        font = QtGui.QFont()
        font.setFamily("細明體")
        font.setPointSize(12)
        self.txt_sysmsg.setFont(font)
        self.txt_sysmsg.setObjectName("txt_sysmsg")
        self.le_device = QtWidgets.QLineEdit(self.centralwidget)
        self.le_device.setGeometry(QtCore.QRect(240, 50, 221, 31))
        font = QtGui.QFont()
        font.setFamily("細明體")
        font.setPointSize(12)
        self.le_device.setFont(font)
        self.le_device.setObjectName("le_device")
        self.getdevice_btn = QtWidgets.QPushButton(self.centralwidget)
        self.getdevice_btn.setGeometry(QtCore.QRect(240, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.getdevice_btn.setFont(font)
        self.getdevice_btn.setObjectName("getdevice_btn")
        self.clearmsg_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clearmsg_btn.setGeometry(QtCore.QRect(760, 17, 111, 31))
        font = QtGui.QFont()
        font.setFamily("標楷體")
        font.setPointSize(12)
        self.clearmsg_btn.setFont(font)
        self.clearmsg_btn.setObjectName("clearmsg_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 877, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "天堂m-自動轉日記"))
        self.left_btn1.setText(_translate("MainWindow", "日記左格子1"))
        self.left_btn2.setText(_translate("MainWindow", "日記左格子2"))
        self.label.setText(_translate("MainWindow", "模擬器類型"))
        self.label_2.setText(_translate("MainWindow", "模擬器畫面尺寸"))
        self.start_btn.setText(_translate("MainWindow", "開始自動轉日記"))
        self.end_btn.setText(_translate("MainWindow", "退出程式"))
        self.label_3.setText(_translate("MainWindow", "自動取得日記本物品次數 :"))
        self.right_btn1.setText(_translate("MainWindow", "日記右格子1"))
        self.right_btn2.setText(_translate("MainWindow", "日記右格子2"))
        self.lab_displaydiraycount.setText(_translate("MainWindow", "1"))
        self.lab_sysmsg.setText(_translate("MainWindow", "系統訊息"))
        self.setdevice_btn.setText(_translate("MainWindow", "set device"))
        self.getdevice_btn.setText(_translate("MainWindow", "get device"))
        self.clearmsg_btn.setText(_translate("MainWindow", "清除訊息內容"))
